# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  watch:
    types: started
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        
    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Update list
      run : |
        echo "$(date)" > output/.lastrun
        npm ci
        node download --output output/all-cdn.txt

        for f in providers/*.js; do 
          FILENAME=${f%%.*}; 
          FILENAME=${FILENAME##*/}; 
          node download --provider ${FILENAME} --output output/${FILENAME}.txt;  
        done;
        
      uses: actions/upload-artifact@v4
      with:
        path: output/

     - name: Apply
      run: |
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
