name: Node.js CI

on:
  watch:
    types: started
  schedule:
    - cron: '00 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
    
    - name: Download list
      run : |
        echo "$(date)" > output/.lastrun
        npm install
        npm audit fix
        npm audit fix --force
        npm audit

        node download --output output/all-cdn.txt

        for f in providers/*.js; do 
          FILENAME=${f%%.*}; 
          FILENAME=${FILENAME##*/}; 
          node download --provider ${FILENAME} --output output/${FILENAME}.txt;  
        done;

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        path: output/
        
    - name: Apply
      run: |
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
