# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/15 * * * *'

jobs:
  download:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: node download --output output/all-cdn.txt
    - uses: actions/upload-artifact@v2
      with:
        path: output/
    - run: |
        git config --global user.name 'node.js Action'
        git config --global user.email 'root@schniggie.de'
        git commit -am "Automated commit, updated cdn ranges"
        git push
